//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatCoach.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routes
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ClubId { get; set; }
        public string URL { get; set; }
        public Nullable<int> Type { get; set; }
        public System.Guid ContentId { get; set; }
    
        public virtual Club Club { get; set; }
    }
}
